package springboot.itheima.dao.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import springboot.itheima.entity.Qx;
import springboot.itheima.entity.QxExample;

public interface QxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qx
     *
     * @mbg.generated Tue Mar 03 15:42:28 CST 2020
     */
    long countByExample(QxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qx
     *
     * @mbg.generated Tue Mar 03 15:42:28 CST 2020
     */
    int deleteByExample(QxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qx
     *
     * @mbg.generated Tue Mar 03 15:42:28 CST 2020
     */
    int insert(Qx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qx
     *
     * @mbg.generated Tue Mar 03 15:42:28 CST 2020
     */
    int insertSelective(Qx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qx
     *
     * @mbg.generated Tue Mar 03 15:42:28 CST 2020
     */
    List<Qx> selectByExample(QxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qx
     *
     * @mbg.generated Tue Mar 03 15:42:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") Qx record, @Param("example") QxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qx
     *
     * @mbg.generated Tue Mar 03 15:42:28 CST 2020
     */
    int updateByExample(@Param("record") Qx record, @Param("example") QxExample example);
}